spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.config.import=configserver:http://localhost:8888

logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"

