spring.application.name=discovery-server
server.port=8761
eureka.instance.hostname=localhost

#Eureka should not register itself
eureka.client.register-with-eureka =false
eureka.client.fetch-registry=false