server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 1509
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

resilience4j: # Dependency
  circuitbreaker:
    instances: # Mentions the instances of circuit-breaker independently

      userServiceBreaker:
        registerHealthIndicator: true # registers health of the service as Up or Down
        slidingWindowSize: 5 # circuitbreaker remembers last 5 calls
        minimumNumberOfCalls: 3 # at least 3 calls happen before calculating failure percentage.(ex. 50% failure)
        failureRateThreshold: 50 # 50% or more request fails, then circuit becomes OPEN
        waitDurationInOpenState: 10s # it blocks all the requests for 10 seconds. allows failed service to recover.
        permittedNumberOfCallsInHalfOpenState: 2 #after 10 seconds allow only 2 test requests.
          #if req successful -> HALF_OPEN becomes CLOSED, if req failure -> HALF_OPEN becomes OPEN
        automaticTransitionFromOpenToHalfOpenEnabled: true # Automatically moves OPEN to HALF_OPEN. without this we should manually reset.

        productServiceBreaker:
          registerHealthIndicator: true
          slidingWindowSize: 5
          minimumNumberOfCalls: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 2
          automaticTransitionFromOpenToHalfOpenEnabled: true

        inventoryServiceBreaker:
          registerHealthIndicator: true
          slidingWindowSize: 5
          minimumNumberOfCalls: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 2
          automaticTransitionFromOpenToHalfOpenEnabled: true

          ignore-exceptions:
            - org.springframework.orm.ObjectOptimisticLockingFailureException

  retry:
    instances:

      userServiceRetry:
        maxAttempts: 3 # Try original call + 2 retries. retries 2 more time to check if was  temporarily down.
        waitDuration: 2s # duration between fail and retry
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2 # instead of fixed wait it becomes 2s,4s,8s

      productServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

      inventoryServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

