spring.application.name=config-server
server.port=8888
spring.cloud.config.server.native.search-locations=classpath:/configs
# By default,spring cloud config assumes mode=git.so to change it to native we are using this
spring.profiles.active=native
